
/** This is a plugin for higlighting items in dragging and selecting
 *	using ctrl + mouse click 
 *	
 * 	@author: Atillo Regner
 *  @author_email: atilloregner@gmail.com
 *  @plugin_name: eHighLight v 1.3
 */

(function(b){b.fn.eHighLight=function(e){function n(a,b){"undefined"!=typeof a.onselectstart?a.onselectstart=function(){return b?!1:!0}:"undefined"!=typeof a.style.MozUserSelect?a.style.MozUserSelect=b?"none":"":(a.onmousedown=function(){return b?!1:!0},a.style.cursor=b?"default":"")}if("removeHighLighted"==e)return this.find("."+f).removeClass(f),!1;e=b.extend({elements:[],startAtBody:!1,mouseMovementDelay:3,onEndDragging:function(){return!1},onStartDragging:function(){return!1},classNameForHighlight:"eHighLight"}, e);var h=e.elements,t=e.mouseMovementDelay,u=e.onEndDragging,v=e.onStartDragging,f=e.classNameForHighlight;e=e.startAtBody?"body":this;var g=this;this.name="sdfsdf";g.last="sdfsdf";var p=!1,c,d,q=[];b(e).mousedown(function(a){c=a.pageX;d=a.pageY;p=!0;v();document.selection?document.selection.empty():window.getSelection().removeAllRanges();n(document.body,!0);return!1});b(document).mouseup(function(){b(".eDragHighLighter").css({top:"-1000px"});n(document.body,!1);q=[];if(p){u();for(var a=0,c=0;c<h.length;c++){var d= h[c];0<g.find(d).length&&g.find(d).each(function(){b(this).hasClass(f)&&(q[a]=b(this),a++)})}}p=!1});for(e=0;e<h.length;e++){var k=b(h[e]);0<g.find(k).length&&g.find(k).click(function(a){if(!0==a.ctrlKey)return b(this).hasClass(f)?b(this).removeClass(f):b(this).addClass(f),!1})}var r=0;b(document).mousemove(function(a){if(p){var e,j,l,m;c<a.pageX&&d<a.pageY?(b(".eDragHighLighter").css({left:c,top:d,bottom:"auto",right:"auto",width:a.pageX-c,height:a.pageY-d}),e=d,j=d+(a.pageY-d),l=c,m=c+(a.pageX- c)):c>a.pageX&&d>a.pageY?(b(".eDragHighLighter").css({left:"auto",top:"auto",bottom:b(window).height()-d,right:b(window).width()-c,width:c-a.pageX,height:d-a.pageY}),e=a.pageY,j=d,l=a.pageX,m=c):c>a.pageX&&d<a.pageY?(b(".eDragHighLighter").css({top:d,bottom:"auto",right:b(window).width()-c,left:"auto",width:c-a.pageX,height:a.pageY-d}),e=d,j=a.pageY,l=a.pageX,m=c):c<a.pageX&&d>a.pageY&&(b(".eDragHighLighter").css({top:"auto",bottom:b(window).height()-d,right:"auto",left:c,width:a.pageX-c,height:d- a.pageY}),e=a.pageY,j=d,l=c,m=a.pageX);r++;if(r<t)return!1;r=0;for(var n=h.length,s=0;s<n;s++){var k=h[s];0<g.find(k).length&&g.find(k).each(function(){var c=b(this).offset();if(c.top<j&&c.left<m&&c.top+b(this).outerHeight()>e&&c.left+b(this).outerWidth()>l){if(b(this).addClass(f),!0==a.ctrlKey)for(var c=q.length,d=0;d<c;d++)q[d][0]==b(this)[0]&&b(this).removeClass(f)}else!1==a.ctrlKey&&b(this).removeClass(f)})}return!1}});1>b("body").find(".eDragHighLighter").length&&b("body").append('<div class="eDragHighLighter"></div>')}})(jQuery);